### ISSUE TITLE
Using reviewable.io for the review process

### ISSUE THREAD

**Issue by szledan** [GepardGraphics/gepard#32]
Link: https://reviewable.io/

**Comment by dbatyai** [comment]
Would using it provide any actual benefits, or just a fancy new UI?

**Comment by kkristof** [comment]
I've checked the demo of the reviewable. I think it is over complicated, while it is really slow, so at the moment I don't see any benefits of using this. 
If there is no objection, then I'm going to close this issue tomorrow.
