### ISSUE TITLE
Renaming macros/defines according to coding-style

### ISSUE THREAD

**Issue by szledan** [GepardGraphics/gepard#68]
See: [Coding-style#defines](https://github.com/GepardGraphics/gepard/wiki/Coding-style#defines)

**Comment by kkristof** [comment]
@szledan this can be closed? Only the `ASSERT` and the `NOT_IMPLEMENTED` macros aren't prefixed with `GD`.

**Comment by szledan** [comment]
Hi @kkristof , I have a solution for this issue. ([68-renaming-macros-according-to-coding-style](https://github.com/szledan/gepard/tree/68-renaming-macros-according-to-coding-style))

**Comment by kkristof** [comment]
cool

**Comment by szledan** [comment]
After #76 has merged, I will close.
