### ISSUE TITLE
[vulkan] Investigate the Vulkan API

### ISSUE THREAD

**Issue by kkristof** [GepardGraphics/gepard#8]
The Khronos's Vulkan API is one of the state of the art graphics library.
For further reference check the http://vulkan.io
As part of the investigation create small example which uses the Vulkan API.

**Comment by kkristof** [comment]
I think this issue could be closed now. @szledan what is your opinion about this?

**Comment by szledan** [comment]
Yep, you are right!
(We know everything about this. ☺)
