### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by dati91** [GepardGraphics/gepard#96]
The `build-essential` package should be added to the dependencies.

If not installed the following error will occur when you try to build:
`cmake fails with “CMake Error: your CXX compiler: ”CMAKE_CXX_COMPILER-NOTFOUND“ was not found.”`

**Comment by kkristof** [comment]
I'm not fond of adding this package to the dependencies as it isn't available on every linux distribution and the developers should be able to choose their compiler as their own.

**Comment by kkristof** [comment]
Wontfix
